import { PLACEHOLDER_TRANSLATIONS } from './placeholders';

export type Language = keyof typeof PLACEHOLDER_TRANSLATIONS;

export const LANGUAGES: Language[] = [
  "Afrikaans (ZA)",
  "Albanian (AL)",
  "Amharic (ET)",
  "Arabic (SA)",
  "Armenian (AM)",
  "Assamese (IN)",
  "Azerbaijani (AZ)",
  "Bangla (BD)",
  "Basque (ES)",
  "Belarusian (BY)",
  "Bosnian (BA)",
  "Bulgarian (BG)",
  "Catalan (ES)",
  "Cebuano (PH)",
  "Chinese (CN)",
  "Croatian (HR)",
  "Czech (CZ)",
  "Danish (DK)",
  "Dutch (NL)",
  "English (US)",
  "Esperanto (EO)",
  "Estonian (EE)",
  "Finnish (FI)",
  "French (FR)",
  "Galician (ES)",
  "Georgian (GE)",
  "German (DE)",
  "Greek (GR)",
  "Gujarati (IN)",
  "Haitian Creole (HT)",
  "Hausa (NG)",
  "Hebrew (IL)",
  "Hindi (IN)",
  "Hmong (US)",
  "Hungarian (HU)",
  "Icelandic (IS)",
  "Igbo (NG)",
  "Indonesian (ID)",
  "Irish (IE)",
  "Italian (IT)",
  "Japanese (JP)",
  "Javanese (ID)",
  "Kannada (IN)",
  "Kazakh (KZ)",
  "Khmer (KH)",
  "Korean (KR)",
  "Kurdish (IQ)",
  "Kyrgyz (KG)",
  "Lao (LA)",
  "Latin (LA)",
  "Latvian (LV)",
  "Lithuanian (LT)",
  "Luxembourgish (LU)",
  "Macedonian (MK)",
  "Malagasy (MG)",
  "Malay (MY)",
  "Malayalam (IN)",
  "Maltese (MT)",
  "Maori (NZ)",
  "Marathi (IN)",
  "Mongolian (MN)",
  "Myanmar (Burmese) (MM)",
  "Nepali (NP)",
  "Norwegian (NO)",
  "Odia (Oriya) (IN)",
  "Pashto (AF)",
  "Persian (IR)",
  "Polish (PL)",
  "Portuguese (PT)",
  "Punjabi (IN)",
  "Romanian (RO)",
  "Russian (RU)",
  "Samoan (WS)",
  "Scots Gaelic (GB)",
  "Serbian (RS)",
  "Sesotho (LS)",
  "Shona (ZW)",
  "Sindhi (IN)",
  "Sinhala (LK)",
  "Slovak (SK)",
  "Slovenian (SI)",
  "Somali (SO)",
  "Spanish (ES)",
  "Sundanese (ID)",
  "Swahili (TZ)",
  "Swedish (SE)",
  "Tagalog (PH)",
  "Tajik (TJ)",
  "Tamil (IN)",
  "Telugu (IN)",
  "Thai (TH)",
  "Turkish (TR)",
  "Ukrainian (UA)",
  "Urdu (IN)",
  "Uyghur (CN)",
  "Uzbek (UZ)",
  "Vietnamese (VN)",
  "Welsh (GB)",
  "Xhosa (ZA)",
  "Yiddish (IL)",
  "Yoruba (NG)",
  "Zulu (ZA)"
];

export default LANGUAGES; 