export const PLACEHOLDER_TRANSLATIONS = {
  "Afrikaans (ZA)": "Tik jou boodskap...",
  "Albanian (AL)": "Shkruaj mesazhin tënd...",
  "Amharic (ET)": "መልእክትዎን ይጻፉ...",
  "Arabic (SA)": "اكتب رسالتك...",
  "Armenian (AM)": "Գրեք ձեր հաղորդագրությունը...",
  "Assamese (IN)": "আপোনাৰ বাৰ্তা লিখক...",
  "Azerbaijani (AZ)": "Mesajınızı yazın...",
  "Bangla (BD)": "আপনার বার্তা লিখুন...",
  "Basque (ES)": "Idatzi zure mezua...",
  "Belarusian (BY)": "Напішыце сваё паведамленне...",
  "Bosnian (BA)": "Napišite svoju poruku...",
  "Bulgarian (BG)": "Напишете вашето съобщение...",
  "Catalan (ES)": "Escriu el teu missatge...",
  "Cebuano (PH)": "Isulat ang imong mensahe...",
  "Chinese (CN)": "输入您的信息...",
  "Croatian (HR)": "Upišite svoju poruku...",
  "Czech (CZ)": "Napište svou zprávu...",
  "Danish (DK)": "Skriv din besked...",
  "Dutch (NL)": "Typ je bericht...",
  "English (US)": "Type your message...",
  "Esperanto (EO)": "Tajpu vian mesaĝon...",
  "Estonian (EE)": "Kirjuta oma sõnum...",
  "Finnish (FI)": "Kirjoita viestisi...",
  "French (FR)": "Tapez votre message...",
  "Galician (ES)": "Escribe a túa mensaxe...",
  "Georgian (GE)": "დაწერეთ თქვენი შეტყობინება...",
  "German (DE)": "Geben Sie Ihre Nachricht ein...",
  "Greek (GR)": "Πληκτρολογήστε το μήνυμά σας...",
  "Gujarati (IN)": "તમારો સંદેશ લખો...",
  "Haitian Creole (HT)": "Tape mesaj ou a...",
  "Hausa (NG)": "Rubuta sakonka...",
  "Hebrew (IL)": "כתוב את ההודעה שלך...",
  "Hindi (IN)": "अपना संदेश लिखें...",
  "Hmong (US)": "Sau koj cov lus...",
  "Hungarian (HU)": "Írja be az üzenetét...",
  "Icelandic (IS)": "Skrifaðu skilaboðin þín...",
  "Igbo (NG)": "Dee ozi gị...",
  "Indonesian (ID)": "Ketik pesan Anda...",
  "Irish (IE)": "Scríobh do theachtaireacht...",
  "Italian (IT)": "Scrivi il tuo messaggio...",
  "Japanese (JP)": "メッセージを入力...",
  "Javanese (ID)": "Ketik pesen sampeyan...",
  "Kannada (IN)": "ನಿಮ್ಮ ಸಂದೇಶವನ್ನು ಬರೆಯಿರಿ...",
  "Kazakh (KZ)": "Хабарыңызды жазыңыз...",
  "Khmer (KH)": "សរសេរសាររបស់អ្នក...",
  "Korean (KR)": "메시지를 입력하세요...",
  "Kurdish (IQ)": "Peyama xwe binivîse...",
  "Kyrgyz (KG)": "Кабарыңызды жазыңыз...",
  "Lao (LA)": "ຂຽນຂໍ້ຄວາມຂອງເຈົ້າ...",
  "Latin (LA)": "Scribe nuntium tuum...",
  "Latvian (LV)": "Rakstiet savu ziņojumu...",
  "Lithuanian (LT)": "Įveskite savo pranešimą...",
  "Luxembourgish (LU)": "Gitt Äre Message an...",
  "Macedonian (MK)": "Напишете ја вашата порака...",
  "Malagasy (MG)": "Soraty ny hafatrao...",
  "Malay (MY)": "Taip mesej anda...",
  "Malayalam (IN)": "നിങ്ങളുടെ സന്ദേശം എഴുതുക...",
  "Maltese (MT)": "Ikteb il-messaġġ tiegħek...",
  "Maori (NZ)": "Tuhia tāu karere...",
  "Marathi (IN)": "तुमचा संदेश लिहा...",
  "Mongolian (MN)": "Мессежээ бичнэ үү...",
  "Myanmar (Burmese) (MM)": "မက်ဆေ့ချ် ရိုက်ထည့်ပါ...",
  "Nepali (NP)": "आफ्नो सन्देश लेख्नुहोस्...",
  "Norwegian (NO)": "Skriv meldingen din...",
  "Odia (Oriya) (IN)": "ଆପଣଙ୍କ ବାର୍ତ୍ତା ଲେଖନ୍ତୁ...",
  "Pashto (AF)": "خپل پیغام ولیکئ...",
  "Persian (IR)": "پیام خود را بنویسید...",
  "Polish (PL)": "Wpisz swoją wiadomość...",
  "Portuguese (PT)": "Escreva a sua mensagem...",
  "Punjabi (IN)": "ਆਪਣਾ ਸੁਨੇਹਾ ਲਿਖੋ...",
  "Romanian (RO)": "Scrieți mesajul dvs...",
  "Russian (RU)": "Введите ваше сообщение...",
  "Samoan (WS)": "Tusi lau feau...",
  "Scots Gaelic (GB)": "Sgrìobh do theachdaireachd...",
  "Serbian (RS)": "Упишите своју поруку...",
  "Sesotho (LS)": "Ngola molaetsa oa hau...",
  "Shona (ZW)": "Nyora meseji yako...",
  "Sindhi (IN)": "پنھنجو پيغام لکو...",
  "Sinhala (LK)": "ඔබගේ පණිවිඩය ලියන්න...",
  "Slovak (SK)": "Napíšte svoju správu...",
  "Slovenian (SI)": "Vnesite svoje sporočilo...",
  "Somali (SO)": "Qor fariintaada...",
  "Spanish (ES)": "Escribe tu mensaje...",
  "Sundanese (ID)": "Tulis pesen anjeun...",
  "Swahili (TZ)": "Andika ujumbe wako...",
  "Swedish (SE)": "Skriv ditt meddelande...",
  "Tagalog (PH)": "I-type ang iyong mensahe...",
  "Tajik (TJ)": "Паёми худро нависед...",
  "Tamil (IN)": "உங்கள் செய்தியை உள்ளிடவும்...",
  "Telugu (IN)": "మీ సందేశాన్ని టైప్ చేయండి...",
  "Thai (TH)": "พิมพ์ข้อความของคุณ...",
  "Turkish (TR)": "Mesajınızı yazın...",
  "Ukrainian (UA)": "Введіть ваше повідомлення...",
  "Urdu (IN)": "اپنا پیغام لکھیں...",
  "Uyghur (CN)": "خېتىڭىزنى يېزىڭ...",
  "Uzbek (UZ)": "Xabaringizni yozing...",
  "Vietnamese (VN)": "Nhập tin nhắn của bạn...",
  "Welsh (GB)": "Teipiwch eich neges...",
  "Xhosa (ZA)": "Chwetheza umyalezo wakho...",
  "Yiddish (IL)": "שרייב דיין מעסעדזש...",
  "Yoruba (NG)": "Kọ ifiranṣẹ rẹ...",
  "Zulu (ZA)": "Thayipha umyalezo wakho..."
};

export default PLACEHOLDER_TRANSLATIONS; 