export const PLACEHOLDER_TRANSLATIONS = {
  "Afrikaans": "Tik jou boodskap...",
  "Albanian": "Shkruaj mesazhin tënd...",
  "Amharic": "መልእክትዎን ይጻፉ...",
  "Arabic": "اكتب رسالتك...",
  "Armenian": "Գրեք ձեր հաղորդագրությունը...",
  "Assamese": "আপোনাৰ বাৰ্তা লিখক...",
  "Azerbaijani": "Mesajınızı yazın...",
  "Bangla": "আপনার বার্তা লিখুন...",
  "Basque": "Idatzi zure mezua...",
  "Belarusian": "Напішыце сваё паведамленне...",
  "Bosnian": "Napišite svoju poruku...",
  "Bulgarian": "Напишете вашето съобщение...",
  "Catalan": "Escriu el teu missatge...",
  "Cebuano": "Isulat ang imong mensahe...",
  "Chinese": "输入您的信息...",
  "Croatian": "Upišite svoju poruku...",
  "Czech": "Napište svou zprávu...",
  "Danish": "Skriv din besked...",
  "Dutch": "Typ je bericht...",
  "English": "Type your message...",
  "Esperanto": "Tajpu vian mesaĝon...",
  "Estonian": "Kirjuta oma sõnum...",
  "Finnish": "Kirjoita viestisi...",
  "French": "Tapez votre message...",
  "Galician": "Escribe a túa mensaxe...",
  "Georgian": "დაწერეთ თქვენი შეტყობინება...",
  "German": "Geben Sie Ihre Nachricht ein...",
  "Greek": "Πληκτρολογήστε το μήνυμά σας...",
  "Gujarati": "તમારો સંદેશ લખો...",
  "Haitian Creole": "Tape mesaj ou a...",
  "Hausa": "Rubuta sakonka...",
  "Hebrew": "כתוב את ההודעה שלך...",
  "Hindi": "अपना संदेश लिखें...",
  "Hmong": "Sau koj cov lus...",
  "Hungarian": "Írja be az üzenetét...",
  "Icelandic": "Skrifaðu skilaboðin þín...",
  "Igbo": "Dee ozi gị...",
  "Indonesian": "Ketik pesan Anda...",
  "Irish": "Scríobh do theachtaireacht...",
  "Italian": "Scrivi il tuo messaggio...",
  "Japanese": "メッセージを入力...",
  "Javanese": "Ketik pesen sampeyan...",
  "Kannada": "ನಿಮ್ಮ ಸಂದೇಶವನ್ನು ಬರೆಯಿರಿ...",
  "Kazakh": "Хабарыңызды жазыңыз...",
  "Khmer": "សរសេរសាររបស់អ្នក...",
  "Korean": "메시지를 입력하세요...",
  "Kurdish": "Peyama xwe binivîse...",
  "Kyrgyz": "Кабарыңызды жазыңыз...",
  "Lao": "ຂຽນຂໍ້ຄວາມຂອງເຈົ້າ...",
  "Latin": "Scribe nuntium tuum...",
  "Latvian": "Rakstiet savu ziņojumu...",
  "Lithuanian": "Įveskite savo pranešimą...",
  "Luxembourgish": "Gitt Äre Message an...",
  "Macedonian": "Напишете ја вашата порака...",
  "Malagasy": "Soraty ny hafatrao...",
  "Malay": "Taip mesej anda...",
  "Malayalam": "നിങ്ങളുടെ സന്ദേശം എഴുതുക...",
  "Maltese": "Ikteb il-messaġġ tiegħek...",
  "Maori": "Tuhia tāu karere...",
  "Marathi": "तुमचा संदेश लिहा...",
  "Mongolian": "Мессежээ бичнэ үү...",
  "Myanmar (Burmese)": "မက်ဆေ့ချ် ရိုက်ထည့်ပါ...",
  "Nepali": "आफ्नो सन्देश लेख्नुहोस्...",
  "Norwegian": "Skriv meldingen din...",
  "Odia (Oriya)": "ଆପଣଙ୍କ ବାର୍ତ୍ତା ଲେଖନ୍ତୁ...",
  "Pashto": "خپل پیغام ولیکئ...",
  "Persian": "پیام خود را بنویسید...",
  "Polish": "Wpisz swoją wiadomość...",
  "Portuguese": "Escreva a sua mensagem...",
  "Punjabi": "ਆਪਣਾ ਸੁਨੇਹਾ ਲਿਖੋ...",
  "Romanian": "Scrieți mesajul dvs...",
  "Russian": "Введите ваше сообщение...",
  "Samoan": "Tusi lau feau...",
  "Scots Gaelic": "Sgrìobh do theachdaireachd...",
  "Serbian": "Упишите своју поруку...",
  "Sesotho": "Ngola molaetsa oa hau...",
  "Shona": "Nyora meseji yako...",
  "Sindhi": "پنھنجو پيغام لکو...",
  "Sinhala": "ඔබගේ පණිවිඩය ලියන්න...",
  "Slovak": "Napíšte svoju správu...",
  "Slovenian": "Vnesite svoje sporočilo...",
  "Somali": "Qor fariintaada...",
  "Spanish": "Escribe tu mensaje...",
  "Sundanese": "Tulis pesen anjeun...",
  "Swahili": "Andika ujumbe wako...",
  "Swedish": "Skriv ditt meddelande...",
  "Tagalog": "I-type ang iyong mensahe...",
  "Tajik": "Паёми худро нависед...",
  "Tamil": "உங்கள் செய்தியை உள்ளிடவும்...",
  "Telugu": "మీ సందేశాన్ని టైప్ చేయండి...",
  "Thai": "พิมพ์ข้อความของคุณ...",
  "Turkish": "Mesajınızı yazın...",
  "Ukrainian": "Введіть ваше повідомлення...",
  "Urdu": "اپنا پیغام لکھیں...",
  "Uyghur": "خېتىڭىزنى يېزىڭ...",
  "Uzbek": "Xabaringizni yozing...",
  "Vietnamese": "Nhập tin nhắn của bạn...",
  "Welsh": "Teipiwch eich neges...",
  "Xhosa": "Chwetheza umyalezo wakho...",
  "Yiddish": "שרייב דיין מעסעדזש...",
  "Yoruba": "Kọ ifiranṣẹ rẹ...",
  "Zulu": "Thayipha umyalezo wakho..."
};

export default PLACEHOLDER_TRANSLATIONS; 